[package]
name = "saddle-interaction-example-vehicle-entry"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bevy = { workspace = true }
bevy_enhanced_input = { workspace = true }
avian3d = { workspace = true }
saddle-interaction = { workspace = true }
saddle-vehicle-ground-vehicle = { workspace = true }
saddle-interaction-example-common = { path = "../common" }

[lints]
workspace = true
