[package]
name = "saddle-interaction-example-chained"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bevy = { workspace = true }
saddle-interaction = { workspace = true }
saddle-interaction-example-common = { path = "../common" }
saddle-pane = { workspace = true }

[lints]
workspace = true
